// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = string
  })
}
variable "dns" {
  type = object({
    enabled     = optional(bool)
    hosted_zone = optional(string)
    sub_domain  = optional(string)
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "monitoring" {
  type = object({
    mode = optional(string)
    alarms = optional(object({
      client_errors = optional(object({
        period    = number
        threshold = number
      }))
      latency = optional(object({
        period    = number
        threshold = number
      }))
      server_errors = optional(object({
        period    = number
        threshold = number
      }))
    }))
  })
  default = null
}
variable "rest_api" {
  type = object({
    endpoint_configuration = string
    region                 = string
    stage_name             = string
  })
}
